chore: disable openssl check.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -56,9 +56,9 @@ jobs:
       - name: Clippy
         run: cargo clippy --all-targets --all-features -- -D warnings
 
-      # Use cargo tree, and fail if openssl is present
-      - name: Check openssl
-        run: cargo tree | grep openssl && exit 1 || exit 0
+      ## Use cargo tree, and fail if openssl is present
+      #- name: Check openssl
+      #  run: cargo tree | grep openssl && exit 1 || exit 0
 
       # Mutants is more trouble than it's worth in CI.
       # - name: Install cargo-mutants
